sudo: required
dist: trusty
language: cpp

services:
  - docker

cache:
  directories:
    - /tmp/docker

env:
  global:
    - "IMAGE=nefelinetworks/bess_build:latest"
  matrix:
    - VER_CXX=g++-4.8 VER_CC=gcc-4.8
    - VER_CXX=g++-5 VER_CC=gcc-5
    - VER_CXX=g++-6 VER_CC=gcc-6

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - if [[ -d /tmp/docker ]]; then ls /tmp/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

install:
  - sudo apt-get install -y g++-4.8 g++-5 g++-6 g++
  - sudo apt-get install -y python
  - ln -s /build/dpdk-16.07 deps
  - docker pull $IMAGE

before_script:
  - sudo sysctl -w vm.nr_hugepages=1024
  - sudo mkdir -p /mnt/huge
  - sudo mount -t hugetlbfs nodev /mnt/huge
  - export CXX=$VER_CXX
  - export CC=$VER_CC

script:
  - ./container_build.py bess
  - ./container_build.py kmod_buildtest
  - sudo bin/bessd -g

before_cache:
  - >
    mkdir -p /tmp/docker && docker images $IMAGE --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e /tmp/docker/$1.tar.gz || docker save $0 | gzip -2 > /tmp/docker/$1.tar.gz'

notifications:
  slack: nefeli:x5udJ7nDIKjCaCrRYprGc4mw
