sudo: required
dist: trusty
language: cpp

services:
  - docker

env:
  - CXX=g++-4.8 CC=gcc-4.8
  - CXX=g++-5 CC=gcc-5
  - CXX=g++-6 CC=gcc-6

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update

install:
  - sudo apt-get install -y g++-6 g++
  - sudo apt-get install -y python
  - docker pull nefelinetworks/bess_build:latest

before_script:
  - sudo sysctl -w vm.nr_hugepages=1024
  - sudo mkdir -p /mnt/huge
  - sudo mount -t hugetlbfs nodev /mnt/huge

script:
  - ls /usr/lib/x86_64-linux-gnu/libstd* -al
  - ./container_build.py
  - ./container_build.py kmod_buildtest
  - sudo bin/bessd -g

notifications:
  slack: nefeli:x5udJ7nDIKjCaCrRYprGc4mw
