sudo: required
dist: trusty
language: cpp

services:
  - docker

env:
  - CXX=g++-4.7 CC=gcc-4.7
  - CXX=g++-5 CC=gcc-5
  - CXX=g++-6 CC=gcc-6

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update

install:
  - sudo apt-get install -y python
  - docker pull nefelinetworks/buildsrv

before_script:
  - sudo sysctl -w vm.nr_hugepages=1024
  - sudo mkdir -p /mnt/huge
  - sudo mount -t hugetlbfs nodev /mnt/huge

script:
  - container_build.py
  - container_build.py kmod_buildtest
  - sudo bin/bessd -g

notifications:
  slack: nefeli:x5udJ7nDIKjCaCrRYprGc4mw
