sudo: required
dist: trusty
language: cpp

services:
  - docker

env:
  - CXX=g++-4.8 CC=gcc-4.8
  - CXX=g++-5 CC=gcc-5
  - CXX=g++-6 CC=gcc-6

before_install:
  - sudo apt-get -q update

install:
  - "wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-5/libstdc++6_5.4.0-6ubuntu1~16.04.2_amd64.deb"
  - sudo dpkg -i libstdc++6_5.4.0-6ubuntu1~16.04.2_amd64.deb
  - sudo apt-get install -y libstdc++6
  - sudo apt-get install -y python
  - docker pull nefelinetworks/bess_build:latest

before_script:
  - sudo sysctl -w vm.nr_hugepages=1024
  - sudo mkdir -p /mnt/huge
  - sudo mount -t hugetlbfs nodev /mnt/huge

script:
  - strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep CXX
  - ./container_build.py
  - ./container_build.py kmod_buildtest
  - sudo bin/bessd -g

notifications:
  slack: nefeli:x5udJ7nDIKjCaCrRYprGc4mw
