- include: packages.yml

- hosts: all
  tags: build-bess
  tasks:
    - name: Enable huge pages
      sysctl: name=vm.nr_hugepages value=1024 sysctl_set=yes
      become: true

    - name: Mount up /mnt/huge
      mount: name=/mnt/huge fstype=hugetlbfs src=none state=mounted
      become: true

    - name: Clone BESS repository
      git: repo=https://github.com/NetSys/bess.git dest={{ ansible_env.HOME }}/bess accept_hostkey=yes
      
    - name: Build BESS (this may take a while)
      shell: ./build.py chdir={{ ansible_env.HOME }}/bess 

    - name: Set PATH
      lineinfile: dest=/etc/environment line='PATH="/opt/bess/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
      become: true
