# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2024 Intel Corporation

name: Release Push Image Workflow

on:
  workflow_dispatch:

jobs:
  docker-build-push-images:
    runs-on: ubuntu-20.04

    env:
      REGISTRY: docker.io
      DOCKER_REGISTRY: docker.io/
      DOCKER_REPOSITORY: cdac5gc/
      RELEASE_VERSION: 0.0.4

    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DCKRUSER }}
        password: ${{ secrets.DCKRPASS }}
    - name: Build and push new BESS base image
      run: yes y | ./env/rebuild_images.py focal64

    - name: FOSSA scan
      uses: fossa-contrib/fossa-action@v3
      with:
        fossa-api-key: 0c3bbcdf20e157bbd487dae173751b28